# Включаем все правила по умолчанию
select = ["E", "F", "B", "I"]

# Игнорируем некоторые правила
ignore = []

# Длина строки
line-length = 88

# Целевая версия Python
target-version = "py311"

[per-file-ignores]
"__init__.py" = ["F401"]

[isort]
combine-as-imports = true
known-first-party = ["locallibrary"]
